### ISSUE TITLE
Request: Timer option for random loot crate

### ISSUE THREAD

**Issue by ruyanve** [Zairus/WeaponCaseLoot#1]
Hey guys, my friends and me love this mod, had a couple wild dungeon runs with it! :-)

So we were thinking the other night and came up with an idea for a pvp server for us and one thing we wanted was time based random loot spawns. 

I know that [Lucky Cases](http://minecraft.curseforge.com/projects/lucky-cases?gameCategorySlug=mc-mods&projectID=244324) adds exactly what we need but I figured I'd rather ask you first... "Fragen kostet nix" as we say in Germany 

At first glance we thought about config option, when enabled lets you choose interval length, a blacklist/whitelist kind of deal for specific crate types and a way to add (mod) items to crates.

Any of the above would be awesome, but I'd name my first born after you if you manage it all, add a bunch of new stuff like armors and shields and release it for 1.9.4! :-P

Anyways, cheers and keep it up

**Comment by tei06398** [comment]
As this mod is open source, I could work on what you want to do as a separate mod entirely. Just PM me, for more information.

-tei06398 (Inferno09)

**Comment by WinterGrave** [comment]
Hi there.

Thanks fo rthe suggestion, I don't think we will add item spawns from other mods at the moment, and yes its very probable we have shields in 1.9.4, also some other features we can add in 1.9, li ke weapon speed.

About spawn random loot at intervals, I am working on another mod that you can find interesting, but not 100% done yet, it's called Random Restockable Crates and you can add loot from any other mod.

**Comment by ruyanve** [comment]
@tei06398 Cheers mate, I don't know if this merits a separate mod, like I said Lucky Cases does exactly what I am looking for. I just like the feel of this mod A LOT better! :-)

@WinterGrave Your crate mod looks nice, but we thought about the crate option and agreed that we don't want to promote camping at these crates and a case spawned in the inventory would be the better way to go for us.

Guess I'll have to go with lucky cases then, anyways here's a quick German translation of your lang file: https://gist.github.com/ruyanve/c48c6bd0f250dd9bfbf08e5df2743168

Cheers guys!
